name = "lchaty-subscribe"
account_id = "978ce9da162df0978b71cdf344fa8126"
compatibility_date = "2025-10-03"
main = "workers/form_worker.js"

# Route to bind the worker to your custom domain. When publishing with wrangler
# this route will be created/updated. Make sure the zone for lchaty.com is
# available in the Cloudflare account belonging to the account_id above.
routes = ["lchaty.com/api/subscribe"]

# Note: D1 database binding will be added after creation. wrangler expects a
# database_id value, which we will populate once the database is created.

[[d1_databases]]
binding = "LCHATY_BETA"
database_name = "lchaty_beta"
database_id = "55bb593c-0f0e-4b03-990f-61f6e1890717"
