CREATE TABLE IF NOT EXISTS signups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT NOT NULL UNIQUE,
  signup_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  opted_in BOOLEAN DEFAULT 1,
  beta_approved BOOLEAN DEFAULT 0,
  notes TEXT
);
